global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'webstore-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'nodejs-app'
    static_configs:
      - targets: [ 'host.docker.internal:3000' ]
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'kong'
    static_configs:
      - targets: [ 'kong:8001' ]
    metrics_path: '/metrics'